#!/usr/bin/env bash
set -euo pipefail
NAMESPACE=messaging-app
DEPLOYMENT=messaging-app
REPLICAS=${1:-3}

kubectl scale deployment messaging-app-deployment --replicas=3
kubectl get pods
wrk -t4 -c100 -d30s http://<service-ip>:8000/
kubectl top pods
