apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  namespace: messaging-app
spec:
  selector:
    app: messaging-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
